### ISSUE TITLE
Aggregating predictions: mismatch between paper and code

### ISSUE THREAD

**Issue by ducnx** [hhi-aml/ecg-selfsupervised#1]
In the section IV.B of your paper, it is written that "During test time while finetuning, we use test-time-augmentation and crop all *non-overlapping* sequences of length 2.5 seconds ...". 
However, the code [here](https://github.com/hhi-aml/ecg-selfsupervised/blob/11241b48996e74d2cab3760b63e0d72de36b443f/clinical_ts/timeseries_utils.py#L392) will produce *overlapped* segments when you initialize the TimeseriesDatasetCrops module with `stride_length_valid = input_size//2` and `chunkify_valid = False`, as shown in this [function](https://github.com/hhi-aml/ecg-selfsupervised/blob/11241b48996e74d2cab3760b63e0d72de36b443f/clinical_ts/simclr_dataset_wrapper.py#L135).
Can you verify my understanding? Thanks in advance.

**Comment by nstrodt** [comment]
Thank you for spotting this inconsistency and for the careful study of our code. We used the same approach as in our original benchmarking repository https://github.com/helme/ecg_ptbxl_benchmarking/blob/master/code/models/fastai_model.py where we also used overlapping sequences. As far as I recall using overlapping vs. non-overlapping sequences does not have a major effect (whereas using no test-time augmentation definitely has). I just noticed that also the evaluation code in the CPC training script did you non-overlapping sequences- I fixed this for consistency reasons. We will also fix the description in a future version of our manuscript.
