### ISSUE TITLE
About the  results of supervised method in the paper?

### ISSUE THREAD

**Issue by UCASHurui** [hhi-aml/ecg-selfsupervised#3]
Hi, this is very inspiring work, and I want to know how is the linear and fine-tune results are obtained for the supervised methods(as listed in the table2)?

**Comment by nstrodt** [comment]
Hi UCASHurui,
thanks for your interest in our work. Fine-tuning in the supervised setting refers to reinitializing the classification head and training it again (which should match the performance of the original supervised training). Linear evaluation just refers finetuning the classification head starting from randomly initialized weights- we should have introduced these terms more clearly in the paper. Feel free to re-open again if you have additional questions!
Best
Nils
